In [4]:
import pandas as pd

In [2]:
import selenium

In [8]:
#the following script pulls demographic data by zipcode to later crossreference against covid cases

!pip install census

Collecting census
  Downloading census-0.8.14-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: future in /opt/venv/lib/python3.6/site-packages (from census) (0.18.2)
Requirement already satisfied: requests>=1.1.0 in /opt/venv/lib/python3.6/site-packages (from census) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/venv/lib/python3.6/site-packages (from requests>=1.1.0->census) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/venv/lib/python3.6/site-packages (from requests>=1.1.0->census) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/venv/lib/python3.6/site-packages (from requests>=1.1.0->census) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/venv/lib/python3.6/site-packages (from requests>=1.1.0->census) (2.8)
Installing collected packages: census
Successfully installed census-0.8.14
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/opt/venv/bin/python -m pip install --upgrade pip' command.

In [9]:
!pip install us

Collecting us
  Downloading us-2.0.2.tar.gz (14 kB)
Collecting jellyfish==0.6.1
  Downloading jellyfish-0.6.1.tar.gz (132 kB)
     |################################| 132 kB 2.2 MB/s eta 0:00:01    |#################               | 71 kB 2.3 MB/s eta 0:00:01
Building wheels for collected packages: us, jellyfish
  Building wheel for us (setup.py) ... done
  Created wheel for us: filename=us-2.0.2-py3-none-any.whl size=11927 sha256=07590bb8b7194f8442b8e783d7935beb8ea9fd26df262d7753bc139fe0f97f9b
  Stored in directory: /root/.cache/pip/wheels/7c/41/9a/d0f0df54714732dfd740299373792cc1cf709e4b7fee8da12e
  Building wheel for jellyfish (setup.py) ... done
  Created wheel for jellyfish: filename=jellyfish-0.6.1-py3-none-any.whl size=10379 sha256=b85ff69a1b0eeabaf2eabc58c664aec72beb249aa3570b370c481dff1993b241
  Stored in directory: /root/.cache/pip/wheels/ca/7d/61/34766ffb4424b924a89158de5b9161bb42a75c663272d8c51e
Successfully built us jellyfish
Installing collected packages: jellyfish, us
Successfully installed jellyfish-0.6.1 us-2.0.2
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/opt/venv/bin/python -m pip install --upgrade pip' command.

In [10]:
from census import Census
from us import states

In [11]:
import pandas as pd

In [12]:
#my census api key is c7a11721ba3362e4b47283d35c4206422bba721a

c = Census("c7a11721ba3362e4b47283d35c4206422bba721a")

In [60]:
#get the data for Nassau

df_tract_nassau_t = pd.DataFrame(c.acs5.state_county_tract('B03002_001E', states.NY.fips, '059', Census.ALL))
df_tract_nassau_w = pd.DataFrame(c.acs5.state_county_tract('B03002_003E', states.NY.fips, '059', Census.ALL))
df_tract_nassau_b = pd.DataFrame(c.acs5.state_county_tract('B03002_004E', states.NY.fips, '059', Census.ALL))
df_tract_nassau_h = pd.DataFrame(c.acs5.state_county_tract('B03002_012E', states.NY.fips, '059', Census.ALL))

In [61]:
#merge the data for Nassau

df_tract_nassau = pd.merge(df_tract_nassau_t, df_tract_nassau_w, on=['tract','state','county'])
df_tract_nassau = pd.merge(df_tract_nassau, df_tract_nassau_b, on=['tract','state','county'])
df_tract_nassau = pd.merge(df_tract_nassau, df_tract_nassau_h, on=['tract','state','county'])

In [62]:
#get the same data for suffolk

df_tract_suffolk_t = pd.DataFrame(c.acs5.state_county_tract('B03002_001E', states.NY.fips, '103', Census.ALL))
df_tract_suffolk_w = pd.DataFrame(c.acs5.state_county_tract('B03002_003E', states.NY.fips, '103', Census.ALL))
df_tract_suffolk_b = pd.DataFrame(c.acs5.state_county_tract('B03002_004E', states.NY.fips, '103', Census.ALL))
df_tract_suffolk_h = pd.DataFrame(c.acs5.state_county_tract('B03002_012E', states.NY.fips, '103', Census.ALL))

In [63]:
#merge the data for suffolk

df_tract_suffolk = pd.merge(df_tract_suffolk_t, df_tract_suffolk_w, on=['tract','state','county'])
df_tract_suffolk = pd.merge(df_tract_suffolk, df_tract_suffolk_b, on=['tract','state','county'])
df_tract_suffolk = pd.merge(df_tract_suffolk, df_tract_suffolk_h, on=['tract','state','county'])

In [64]:
#union the two dataframes from long island

frames = [df_tract_nassau,df_tract_suffolk]

df_tract_longisland = pd.concat(frames)

In [65]:
df_tract_longisland

     B03002_001E state county   tract  B03002_003E  B03002_004E  B03002_012E
0         1115.0    36    059  981100        640.0        165.0        183.0
1            0.0    36    059  990302          0.0          0.0          0.0
2            0.0    36    059  990200          0.0          0.0          0.0
3         4737.0    36    059  522700       4521.0          3.0        120.0
4         3110.0    36    059  416402       2624.0        140.0        293.0
..           ...   ...    ...     ...          ...          ...          ...
318       4962.0    36    103  190603       2760.0        110.0       1994.0
319       4321.0    36    103  190604       3611.0         10.0        624.0
320       1034.0    36    103  200901        890.0         15.0         63.0
321       7137.0    36    103  200902       5095.0        138.0       1807.0
322          0.0    36    103  990100          0.0          0.0          0.0

[607 rows x 7 columns]

In [66]:
df_tract_longisland = df_tract_longisland.rename(columns={"B03002_001E":"pop_total",\
                                                             "B03002_003E":"pop_white",\
                                                             "B03002_004E":"pop_black",\
                                                             "B03002_012E":"pop_hispanic"})

In [67]:
df_tract_longisland = df_tract_longisland.filter(items=['tract',
                                                         'state', 
                                                         'county',
                                                         'pop_total',
                                                         'pop_white',
                                                         'pop_black',
                                                         'pop_hispanic'])

In [71]:
#write this data to a csv file

df_tract_longisland.to_csv('long_island_tract_demographics.csv',index = False, header=True)

In [44]:
df_tract_longisland = df_tract_longisland[column_selection]

,tract,state_x,state_x,county_x,county_x,pop_total,pop_white,pop_black,pop_hispanic
0,981100,36,36,059,059,1115.0,640.0,165.0,183.0
1,990302,36,36,059,059,0.0,0.0,0.0,0.0
2,990200,36,36,059,059,0.0,0.0,0.0,0.0
3,522700,36,36,059,059,4737.0,4521.0,3.0,120.0
4,416402,36,36,059,059,3110.0,2624.0,140.0,293.0
5,990400,36,36,059,059,0.0,0.0,0.0,0.0
6,982100,36,36,059,059,1366.0,661.0,271.0,182.0
7,980100,36,36,059,059,1012.0,682.0,65.0,108.0
8,416401,36,36,059,059,4283.0,3812.0,32.0,324.0
9,416801,36,36,059,059,2077.0,1755.0,87.0,165.0
10,416802,36,36,059,059,3754.0,3117.0,0.0,594.0
11,990100,36,36,059,059,0.0,0.0,0.0,0.0
12,521902,36,36,059,059,4183.0,3991.0,2.0,155.0
13,990301,36,36,059,059,0.0,0.0,0.0,0.0
14,304203,36,36,059,059,5715.0,103.0,2930.0,2668.0
15,304204,36,36,059,059,5063.0,147.0,1671.0,3091.0
16,406701,36,36,059,059,2813.0,398.0,809.0,1445.0
17,521302,36,36,059,059,5526.0,4854.0,0.0,531.0
18,521500,36,36,059,059,5032.0,4431.0,0.0,339.0
19,406702,36,36,059,059,4529.0,856.0,2261.0,1280.0
20,406801,36,36,059,059,5145.0,185.0,1699.0,3054.0
21,406802,36,36,059,059,4531.0,60.0,1210.0,3243.0
22,407203,36,36,059,059,3294.0,201.0,1757.0,1081.0
23,407204,36,36,059,059,2754.0,256.0,1416.0,890.0
24,414303,36,36,059,059,4879.0,1681.0,1224.0,1862.0
25,414304,36,36,059,059,3183.0,756.0,758.0,1614.0
26,518203,36,36,059,059,4418.0,3450.0,123.0,150.0
27,519704,36,36,059,059,3096.0,2249.0,0.0,157.0
28,520100,36,36,059,059,5522.0,4990.0,5.0,109.0
29,521602,36,36,059,059,3250.0,2948.0,0.0,143.0
...,...,...,...,...,...,...,...,...,...
293,146403,36,36,103,103,4816.0,845.0,1366.0,2423.0
294,146404,36,36,103,103,3472.0,1163.0,782.0,1503.0
295,147200,36,36,103,103,6788.0,2862.0,1004.0,2654.0
296,146608,36,36,103,103,2706.0,1931.0,0.0,594.0
297,146611,36,36,103,103,3028.0,2424.0,322.0,161.0
298,146612,36,36,103,103,5072.0,4284.0,156.0,450.0
299,147503,36,36,103,103,1373.0,1283.0,0.0,86.0
300,147601,36,36,103,103,2327.0,2073.0,54.0,130.0
301,158011,36,36,103,103,4575.0,3596.0,7.0,403.0
302,158322,36,36,103,103,1930.0,1605.0,0.0,85.0
303,158323,36,36,103,103,6602.0,5800.0,4.0,547.0
304,158409,36,36,103,103,3989.0,3004.0,184.0,312.0
305,158410,36,36,103,103,3161.0,2976.0,87.0,98.0
306,159411,36,36,103,103,3451.0,2821.0,112.0,499.0
307,159412,36,36,103,103,8277.0,6573.0,408.0,920.0
308,159509,36,36,103,103,2980.0,2184.0,136.0,600.0
309,159510,36,36,103,103,173.0,88.0,0.0,77.0
310,159511,36,36,103,103,7615.0,4118.0,621.0,2124.0
311,159512,36,36,103,103,2319.0,1603.0,107.0,563.0
312,169703,36,36,103,103,1654.0,1460.0,19.0,130.0
313,169704,36,36,103,103,7039.0,5317.0,1037.0,363.0
314,169901,36,36,103,103,6388.0,4041.0,1198.0,1038.0
315,169902,36,36,103,103,4230.0,3617.0,204.0,369.0
316,190503,36,36,103,103,2838.0,2477.0,78.0,283.0
317,190504,36,36,103,103,1748.0,1674.0,14.0,26.0
318,190603,36,36,103,103,4962.0,2760.0,110.0,1994.0
319,190604,36,36,103,103,4321.0,3611.0,10.0,624.0
320,200901,36,36,103,103,1034.0,890.0,15.0,63.0
321,200902,36,36,103,103,7137.0,5095.0,138.0,1807.0
322,990100,36,36,103,103,0.0,0.0,0.0,0.0

In [72]:
len(df_tract_longisland)

607

In [54]:
#this is zipcode information for the whole country

df_zipcode_t = pd.DataFrame(c.acs5.zipcode('B03002_001E', Census.ALL))
df_zipcode_w = pd.DataFrame(c.acs5.zipcode('B03002_003E', Census.ALL))
df_zipcode_b = pd.DataFrame(c.acs5.zipcode('B03002_004E', Census.ALL))
df_zipcode_h = pd.DataFrame(c.acs5.zipcode('B03002_012E', Census.ALL))

In [59]:
#this is how you subset data 
#df_zipcode_t[df_zipcode_t['zip code tabulation area']=='10549']

       B03002_012E zip code tabulation area
24279       4597.0                    10549

In [73]:
#merge all the dataframes into a single dataframe

df_zipcode_all = pd.merge(df_zipcode_t, df_zipcode_w, on='zip code tabulation area')
df_zipcode_all = pd.merge(df_zipcode_all, df_zipcode_b, on='zip code tabulation area')
df_zipcode_all = pd.merge(df_zipcode_all, df_zipcode_h, on='zip code tabulation area')

In [74]:
df_zipcode_all = df_zipcode_all.rename(columns={"B03002_001E":"pop_total",\
                                                  "B03002_003E":"pop_white",\
                                                  "B03002_004E":"pop_black",\
                                                  "B03002_012E":"pop_hispanic"})

In [75]:
df_zipcode_all.to_csv('zip_demographics.csv',index = False, header=True)

In [76]:
df_zipcode_all

       pop_total zip code tabulation area  pop_white  pop_black  pop_hispanic
0         8642.0                    43964     8209.0      256.0          27.0
1        51116.0                    28216    12020.0    32646.0        4077.0
2        71605.0                    28277    47299.0     6154.0        5172.0
3        27286.0                    28278    12758.0     8214.0        2870.0
4        29414.0                    28303    12090.0    11295.0        3084.0
...          ...                      ...        ...        ...           ...
33115      628.0                    98279      590.0        3.0          20.0
33116      417.0                    98280      382.0        0.0          12.0
33117    27856.0                    98311    18822.0     1143.0        2711.0
33118      657.0                    98326      481.0       10.0          64.0
33119    18321.0                    98332    15367.0      318.0         964.0

[33120 rows x 5 columns]